version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=root
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4:8.2
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:123456@postgres:5432/simple_bank?sslmode=disable
      - GIN_MODE=release
    depends_on:
      - postgres
    entrypoint: ["./wait-for.sh", "postgres:5432","--", "/app/start.sh"]
    command: ["./main"]
          